name: deploy to github page

on:
  push:
    branches: [master]
  workflow_run:
    workflows: ["schedule"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cp -r api docs/public/
          cd docs
          yarn install
          yarn build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build # The folder the action should deploy.
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
